sudo: required
services:
 - docker

before_install:
 - docker build -t harpreetbrar1/knowledgebase3 -f Dockerfile.dev .

script:
 - docker run -e CI=true harpreetbrar1/knowledgebase3 npm run start

deploy:
  - provider: elasticbeanstalk
  - access_key_id:
      secure: ""
  - secret_access_key:
      secure: ""
  - region: "us-west-2"
  - app: ""
  - env: ""
  - bucket_name: ""
    
